# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "502e2e8ae82fc11025a626b33c6598a7"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "phatnt-thankyou-status"
handle = "phatnt-thankyou-status"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "my-store-1278.myshopify.com"
include_config_on_deploy = true
