# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12e57226faa3a181842b46918ea9f9c0"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "phatnt local checkout"
handle = "phatnt-local-checkout"

[build]
dev_store_url = "my-store-1278.myshopify.com"
include_config_on_deploy = false

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
