# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db3e528892a779bae3c11074cb14a320"
application_url = "https://example.com/"
embedded = true
name = "phatnt-local-checkout"
handle = "phatnt-local-checkout-1"

[build]
dev_store_url = "phatnt-staging.myshopify.com"
include_config_on_deploy = false

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false
