# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-04"

[[extensions]]
name = "Customization Image Preview"
handle = "customization-image-preview"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.cart-line-item.render-after"
export = "checkoutBlock"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.thank-you.cart-line-item.render-after"
export = "thankyouBlock"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "customer-account.order-status.cart-line-item.render-after"
export = "orderStatusBlock"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
  [[extensions.settings.fields]]
  key = "button_label"
  type = "single_line_text_field"
  name = "Button label"
  default = "Preview"
  description = "If leave empty, \"Preview\" will be used."

  [[extensions.settings.fields]]
  key = "preview_type"
  type = "single_line_text_field"
  name = "Preview type"
  default = "Popover"
  description = "Display of customization image when clicking preview button. If not select, \"Popup\" will be shown by default."
    [[extensions.settings.fields.validations]]
    name = "choices"
    value = "[\"Popover\", \"Popup\", \"Expansible\"]"
